### ISSUE TITLE
consider name?

### ISSUE THREAD

**Issue by ChrisJefferson** [blainehansen/magmide#7]
Hi,

I don't usually like to pick on names, but I often use a different, much older, mathematics related language, magma: https://en.m.wikipedia.org/wiki/Magma_(computer_algebra_system)

I just wanted to check you were aware of it, as I expect if your system gets popular, there will be confusion (in both directions).

**Comment by mleonhard** [comment]
A non-ambiguous name is important.  Here are a few suggestions for new names.  I did a quick web search for each one and found little related to software or programming.
- Janie
- Ellis
- Rhoda

**Comment by blainehansen** [comment]
Agh yeah I was familiar with it, but I managed to lie to myself that the projects were in distinct enough domains or that the computer algebra system wasn't mainstream enough such that it didn't matter. I love the name Magma and was really attached to it, but (:long-sigh:) you're right :(

I'm just going to (roughly) quote what I said when the problem was brought up in this reddit thread:
https://www.reddit.com/r/rust/comments/qx5myo/magma_a_project_i_hope_will_make_provably_correct/

> Agh naming things is hard haha :cry:
> I originally wanted "bedrock" but that's taken by a (private and proprietary!) initiative in the verification space, and since this is an "abstract" system intended to verify arbitrary platforms I thought "magma" or "lava" would be nice since it's "bedrock" that hasn't solidified yet.
> Honestly I think it's not even important for a name to even mean something interesting ha. The name Rust is awesome, but mostly because it's short, easy to remember/say/write, and evocative ha, it makes people feel something sorta related to the language (rust is heavy and industrial and serious) but that doesn't strictly mean anything.
> I'm completely open to ideas!

Here are some of the name ideas I've liked that don't seem taken:

- Rhyo or Ryo
- Bright
- Brunt
- Brazen
- Pragma
- Ice, might overlap with ICE/internet communications engine
- Cryo
- Molt
- Heart

**Comment by tshepang** [comment]
I like it when a chosen name is not a dictionary word, of if it is, that it's misspelled. This helps with being searchable. That is, the choice of "rust" for a programming language is unfortunate.

**Comment by programmerjake** [comment]
how about:
* Boulder
* Nitride
* Magnesium
* Sulfur
* Ironwood

**Comment by glyn** [comment]
Or:

* Basalt
* Dacite
* Lahar

**Comment by Restioson** [comment]
Tuff could be a nice name if it isn't taken

**Comment by programmerjake** [comment]
> Tuff could be a nice name if it isn't taken

I thought of that but decided I didn't like it cuz tuff is usually a quite weak variety of stone.

**Comment by blainehansen** [comment]
Last night I figured out a name that satisfies all the requirements we've been talking about here: Magmide.

- It isn't taken by any existing organization or project.
- It isn't a dictionary word, so it's completely unambiguous.
- It's short, easy to remember/say/read/write.
- It evokes the same rough cloud of "geological" feelings as Magma, plus an "industrialness" that comes along with "ides" like bromide and halide etc (someone on the reddit thread suggested halide which is what I think pushed me in this direction).

I love it ha, and since it's so close to the existing name that I also love, it seems like a no brainer! Thanks everyone! Sorry I didn't choose any of the suggested names, but this one is just too nice a fit.
